"""Description of the changes

Revision ID: c9a72608e2ea
Revises: 
Create Date: 2024-04-25 21:51:33.123658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9a72608e2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scorer_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('assist1_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assist2_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['assist2_id'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['scorer_id'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['assist1_id'], ['id'])
        batch_op.drop_column('assist1')
        batch_op.drop_column('scorer')
        batch_op.drop_column('assist2')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assist2', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('scorer', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('assist1', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'players', ['assist2'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['scorer'], ['id'])
        batch_op.create_foreign_key(None, 'players', ['assist1'], ['id'])
        batch_op.drop_column('assist2_id')
        batch_op.drop_column('assist1_id')
        batch_op.drop_column('scorer_id')

    # ### end Alembic commands ###
