"""empty message

Revision ID: e60678b574ca
Revises: 
Create Date: 2024-05-02 16:46:50.843688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e60678b574ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ScoreboardData',
    sa.Column('ScoreboardDataID', sa.Integer(), nullable=False),
    sa.Column('Clock', sa.String(length=10), nullable=True),
    sa.Column('AwayScore', sa.Integer(), nullable=True),
    sa.Column('HomeScore', sa.Integer(), nullable=True),
    sa.Column('Period', sa.Integer(), nullable=True),
    sa.Column('awaypenplayer1', sa.Integer(), nullable=True),
    sa.Column('awaypenplayer2', sa.Integer(), nullable=True),
    sa.Column('awaypentiime1', sa.String(length=10), nullable=True),
    sa.Column('awaypentiime2', sa.String(length=10), nullable=True),
    sa.Column('homepenplayer1', sa.Integer(), nullable=True),
    sa.Column('homepenplayer2', sa.Integer(), nullable=True),
    sa.Column('homepentiime1', sa.String(length=10), nullable=True),
    sa.Column('homepentiime2', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('ScoreboardDataID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ScoreboardData')
    # ### end Alembic commands ###
